### ISSUE TITLE
Allows to add only a qualifier

### ISSUE THREAD

**Issue by Tpt** [google/primarysources#56] opened 2015-08-22 01:57 UTC
When Primary Sources suggest a new statement with only one or more new qualifiers than an existing statement allow to add these qualifiers to the existing statement instead of suggesting to create a new one.

**Comment by tomayac** [comment] 2016-02-23 15:48
This was regarded out of scope, as the core focus of the tool is sources, not qualifiers. I am closing the issue for now. Do feel free to re-open if you still see this as an area we should focus on.

**Closed by tomayac** 2016-02-23 15:48 UTC

**Comment by lydiapintscher** [comment] 2016-02-23 17:03
I believe this is necessary yes. We for example want to allow suggestions for qualifiers in the case of mayors of a city. It should be possible to suggest the qualifiers for their time in office. This will help us enrich the data more.

**Comment by lydiapintscher** [comment] 2016-02-23 17:03
I can not reopen.

**Comment by tomayac** [comment] 2016-02-25 09:02
Leaving this one closed and following up in https://github.com/google/primarysources/issues/73 instead, which deals with the same root cause.
