### ISSUE TITLE
Merge duplicate references

### ISSUE THREAD

**Issue by marfox** [google/primarysources#54] opened 2015-07-31 10:55 UTC
A dataset may contain multiple QuickStatements with the same reference, but different qualifiers (due to multiple extractions from different sentences in the same text).
See for instance:
`Q43926  P1344   Q15804  P585    +00000002012-03-11T00:00:00Z/11 S854    "http://biografieonline.it/biografia.htm?BioID=2962&biografia=Andrea+Pirlo"`
VS
`Q43926  P1344   Q15804  S854    "http://biografieonline.it/biografia.htm?BioID=2962&biografia=Andrea+Pirlo"`

The reference is currently displayed twice.
See https://www.wikidata.org/wiki/Q43926 .

**Comment by fnielsen** [comment] 2015-10-15 09:21
A perhaps related problem with duplicate references I have seen with Michael Laudrup https://www.wikidata.org/wiki/Q188720 There the *same* qualifier has 3 identical references. (Soccer coach to http://www.transfermarkt.com/michael-laudrup/profil/spieler/8023 with P854 as reference (S854)

**Comment by addshore** [comment] 2016-01-07 19:06
+1

References should be compared using snaks that have one of the key reference properties:

For example imported from / reference URL / stated in

**Comment by tomayac** [comment] 2016-02-25 09:06
Closing, as the root cause is the lack of *qualifier* handling. Tracked in https://github.com/google/primarysources/issues/73 instead.

**Closed by tomayac** 2016-02-25 09:06 UTC
