### ISSUE TITLE
After selecting a dataset, approving a new statement (or a source of a suggested one) makes all (other) suggested sources disappear

### ISSUE THREAD

**Issue by mineo** [google/primarysources#39] opened 2015-07-03 11:14 UTC
To reproduce, switch to the "freebase" dataset in the gadget, go to a random freebase item, approve a new statement, but none of the sources. The page reloads, the new statement appears, none of the sources (that weren't approved, but neither were they rejected) is suggested again.

Alternatively, approve or reject one of the sources. The page reloads, the new statement with the approved source is there. If there were other suggested sources, they're not suggested again

Using the "all sources" dataset works as expected.

**Comment by wastl** [comment] 2015-07-03 11:42
In this case it is a data model issue. Approval or rejection currently is at the statement level, not at the source level. So if a single statement has multiple sources, then the statement is accepted with all its sources. If we want to keep sources separate, it would be necessary to import the statements differently into the backend, i.e. repeat the statement for each source.

Not sure if this is really a bug. We should have a more thorough discussion on this.

**Comment by mineo** [comment] 2015-07-03 12:09
Is the data model after selecting a dataset different from the "all sources" datamodel? Because that one allows approving statements without approving any of the sources.

**Comment by wastl** [comment] 2015-07-03 12:19
No, the problem is in the way statements with multiple sources are represented when they are imported. There are two ways:

    Q123 P456 "abc" source S1 source S2

is represented internally as a single statement with a single approval, whereas

    Q123 P456 "abc" source S1
    Q123 P456 "abc" source S2
   
is represented internally as two statements with each a separate approval. In the initial dataset we had decided to duplicate statements with multiple sources so each statement in the backend only has a single source. Apparently, some of the newer datasets use the single-statement-multiple-sources model.

While it is possible to fix the problem in the backend, this change would have major consequences for the backend and might even have performance problems. I would prefer fixing the problem on the data level instead.

**Comment by wastl** [comment] 2015-07-03 12:19
This is related to #34 .

**Comment by Tpt** [comment] 2015-07-03 19:01
>  If we want to keep sources separate, it would be necessary to import the statements differently into the backend, i.e. repeat the statement for each source.

I believe that it's what is done currently.

> Apparently, some of the newer datasets use the single-statement-multiple-sources model.

I don't think so. The dataset uploaded a few weeks ago (result-06-10) use one statement per source with single snak sources and the one with Freebase ids use also one statement per source but the sources contains two snaks.

> To reproduce, switch to the "freebase" dataset in the gadget, go to a random freebase item, approve a new statement, but none of the sources. 

I believe that what happens here is that the main snak + qualifiers get saved but the statements with the same main snak + qualifiers get approved in the backend. To fix this issue we should maybe not mark as approved a statement with source when only the main snak + qualifiers get approved.

> Alternatively, approve or reject one of the sources. The page reloads, the new statement with the approved source is there. If there were other suggested sources, they're not suggested again

Does it happen only with Freebase ids? If yes, I believe that it is because the frontend does not support yet sources that have two snaks. It is the topic of issue #34

**Comment by mineo** [comment] 2015-07-04 09:30
> Does it happen only with Freebase ids? If yes, I believe that it is because the frontend does not support yet sources that have two snaks. It is the topic of issue #34

After managing to find an item with suggestions other than Freebase ids, it looks like it does not affect all suggestions - I approved the voice actor occupation on https://www.wikidata.org/wiki/Q2468138 by approving http://www.imdb.com/title/tt2809036/.

**Comment by wastl** [comment] 2015-07-06 09:00
If I do a request 

    curl -i "https://tools.wmflabs.org/wikidata-primary-sources/entities/Q7430618?state=any"

I get a result with _two_ sources:

    Q7430618\tP646\t\"/m/0bfvws\"\tS248\tQ20635329\tS577\t+00000002015-02-13T00:00:00Z/11

The second source seems to be a timestamp, and I couldn't find documentation on the property S577 that is used here.

Regarding the "accepting statement including source" issue: I would say this is the correct behaviour. You should not be able to accept a statement without its source. You might be able to accept the statement a second time with a second source, though. Maybe the UI should ensure this is handled this way?

**Comment by mineo** [comment] 2015-07-06 14:06
> Regarding the "accepting statement including source" issue: I would say this is the correct behaviour. You should not be able to accept a statement without its source. You might be able to accept the statement a second time with a second source, though. Maybe the UI should ensure this is handled this way?

If it should only be possible to accept a statement with at least one source, the UI needs to be changed - having an "approve" button next to the statement itself certainly suggests that a statement can be approved without a source. Though I agree - with dataset support, there should be at least one valid source for each statement, which is the dataset.

**Comment by Tpt** [comment] 2015-07-06 17:01
> Maybe the UI should ensure this is handled this way?

I agree with you. I'll work on it today

**Comment by Tpt** [comment] 2015-07-06 21:24
It should be fixed now. Feel free to reopen the bug if it is not the case.

**Closed by Tpt** 2015-07-06 21:24 UTC
